name = "world_knowledge"
merge_output_file = "questions.jsonl"

[[sources]]
name = "mmlu"
enabled = true
provider = "huggingface"
adapter = "mmlu_cais"
output_file = "mmlu.jsonl"
merge_into_world = true

[sources.huggingface]
repo_id = "cais/mmlu"
config_name = ""
revision = "main"

[[sources]]
name = "trivia_qa"
enabled = true
provider = "huggingface"
adapter = "trivia_qa_rc"
output_file = "trivia_qa.jsonl"
merge_into_world = true

[sources.huggingface]
repo_id = "trivia_qa"
config_name = "rc.nocontext"
revision = "main"
